spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: ""

  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true

server:
  port: 8085

eureka:
  instance:
    hostname: "localhost"
  fetch-registry: true
  register-with-eureka: true
  client:
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

  health:
    liveness-state:
      enabled: true
    readiness-state: true

  info:
    env:
      enabled: true

    endpoint:
      shutdown:
        enabled: true

endpoints:
  shutdown:
    enable: true


info:
  app:
    name: ticketing
    description: "local transport system"
    version: "0.0.1"
